# Generated by Django 4.1.7 on 2025-04-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_codigo', models.CharField(max_length=100)),
                ('stock_total', models.IntegerField(default=0)),
                ('stock_carrusel', models.IntegerField(default=0)),
                ('cliente', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad_por_caja', models.IntegerField(default=1)),
                ('promedio_venta', models.IntegerField(default=0)),
                ('promedio_sobredimensionado', models.IntegerField(default=0)),
                ('cantidad_op', models.IntegerField(default=0)),
                ('tipo_ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('unidades_por_batea', models.IntegerField(default=0)),
                ('cantidad_bateas', models.IntegerField(default=0)),
                ('cantidad_max_bateas', models.IntegerField(default=0)),
                ('stock_max_carrusel', models.IntegerField(default=0)),
                ('psicofarmaco', models.CharField(default='No informado', max_length=100)),
            ],
        ),
    ]
