# Generated by Django 4.1.7 on 2025-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_posicion', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('entrando', models.IntegerField(default=0)),
                ('saliendo', models.IntegerField(default=0)),
                ('denominacion', models.CharField(blank=True, max_length=255)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('caducidad', models.CharField(blank=True, max_length=100)),
                ('udc', models.CharField(blank=True, max_length=100)),
                ('uds_udc', models.IntegerField(default=0)),
                ('ultima_entrada', models.CharField(blank=True, max_length=100)),
                ('anchura', models.FloatField(default=0)),
                ('profundidad', models.FloatField(default=0)),
                ('altura', models.FloatField(default=0)),
                ('zona', models.CharField(blank=True, max_length=50)),
                ('equipo', models.CharField(blank=True, max_length=50)),
                ('modulo', models.CharField(blank=True, max_length=50)),
                ('nivel', models.CharField(blank=True, max_length=50)),
                ('fondo', models.CharField(blank=True, max_length=50)),
                ('articulo', models.CharField(blank=True, max_length=100)),
                ('reservado_articulo', models.CharField(blank=True, max_length=50)),
                ('reservado_udc', models.CharField(blank=True, max_length=50)),
                ('fija', models.CharField(blank=True, max_length=50)),
                ('cod_barras', models.CharField(blank=True, max_length=100)),
                ('udc_reserva', models.CharField(blank=True, max_length=100)),
                ('bloqueada', models.CharField(blank=True, max_length=50)),
                ('impedir_entrada', models.CharField(blank=True, max_length=50)),
                ('impedir_salida', models.CharField(blank=True, max_length=50)),
                ('udp', models.CharField(blank=True, max_length=50)),
                ('uds_udp', models.IntegerField(default=0)),
                ('tipo_stock', models.CharField(blank=True, max_length=50)),
                ('propietario', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
