# Generated by Django 4.1.7 on 2025-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_ubicacioncarrusel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('galys', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('cliente', 'codigo')},
            },
        ),
    ]
