# Generated by Django 4.1.7 on 2025-04-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_pedidotemporal_productogeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='productogeneral',
            name='cantidad_por_caja',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productogeneral',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productogeneral',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
    ]
