# Generated by Django 4.1.7 on 2025-04-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_productogeneral_cantidad_por_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidotemporal',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedidotemporal',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
