# Generated by Django 5.1.1 on 2025-04-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_pedidotemporal_lote_alter_pedidotemporal_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoReactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField()),
                ('es_valido', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
